### ISSUE TITLE
Implement a user system / authorization

### ISSUE THREAD

**Issue by rommsen** [SAFE-Stack/SAFE-ConfPlanner#32]
- create new users/organizers
- list of available users/organizers
- add/remove organizers to conference

**Comment by rommsen** [comment]
Should be role based.
Available roles in step 1:
* attendee
* organizer
* admin

A user can be an attendee of a conference and an organizer of a different conference.
Admins should be hard coded

I imagine a system in which there exist multiple user/role providers. Each provider can return one or multiple roles for a given user (possible user providers: file, event sourced projection, some online storage)
Each user provider should be async (therefore they can be asked in parallel), the order of execution should not be important and the result of all providers should be combined (i.e the list of roles should be a monoid)

**Comment by mattgallagher92** [comment]
Closing this issue: about to archive repo.
