### ISSUE TITLE
Put it on azure for others to play with

### ISSUE THREAD

**Issue by forki** [SAFE-Stack/SAFE-ConfPlanner#52]

**Comment by rommsen** [comment]
Never done anything with Azure yet. So any help/guidance would be appreciated

**Comment by forki** [comment]
Do you already create a docker container here? If yes then you can push it
to docker hub and I host it on my azure subscription

Am 31.12.2017 15:19 schrieb "Roman Sachse" <notifications@github.com>:

Never done anything with Azure yet. So any help/guidance would be
appreciated

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SAFE-Stack/SAFE-ConfPlanner/issues/52#issuecomment-354606268>,
or mute the thread

**Comment by rommsen** [comment]
So. I am back from holiday hibernation. I am not creating a docker container, yet. I will prepare the docker stuff and come back to you later. Thanks!

**Comment by mattgallagher92** [comment]
Closing this issue: about to archive repo.
