### ISSUE TITLE
Build error on dotnet SDK 2.1.301 and node 10.8.0. Possible missing requirements in README

### ISSUE THREAD

**Issue by MarneeDear** [SAFE-Stack/SAFE-ConfPlanner#60]
I have all of the latest versions of the requirements and had a number of build errors. I was able to correct them by installing a bunch of things. I have a pull request to go along with this issue.

These are the versions I am working with
- dotnet SDK 2.1.301
- npm 6.2.0
- node 10.8.0

I also had Visual Studio 2015 and 2017 installed.

The first build error was related to an npm package that was not compatible with my version of node.
- upath v 1.0.4
In the yarn file I updated it to 1.0.5 and was able to continue building.

npm-gyp was trying to find Python. I had Python 3.6 installed and in my path but npm-gyp was looking for Python 2.7. I ended up installing Python 2.7.

I think the following could be covered by doing an npm command, but I ended up doing them manually because I didn't know about this command. I am not sure it would work, but it looks relevant.

```npm install --global --production windows-build-tools```
https://www.npmjs.com/package/windows-build-tools

There was a step in the build that complained about not finding the Windows 8.1 SDK. I used the Visual Studio 2017 install to install it.

A step in the build was looking for CL.exe. I ended up installing the Desktop Development Environment for C++ in Visual Studio 2017. This seemed to work.

The step where webpack is run 
```...\dotnet.exe fable webpack --port free -- -p --mode production```
Got this error
```ERROR in ./src/Client/Client.fsproj
Module build failed: Error: MSBuild failed with exitCode -2147450735 Working Directory```

I ended up changing the global.json SDK version to the current version (which is the same as in the requirements list).

```{
    "sdk": {
      "version": "2.1.301"
    }
}
```

I have will link a pull request that updates the global.json, yarn files, and adds a note to the README.

Does anyone know if the npm command to install the windows build tools would work instead of using the installer? I think it should also take care of the Python problem, but would it also take care of the failure to find Windows 8.1 SDK?

**Comment by rommsen** [comment]
As I already said. Sorry for the long delay. Everything should work now with the latest netcore sdk and the new readme
