### ISSUE TITLE
build.fsx fails due to PR #67.

### ISSUE THREAD

**Issue by WilliamOckham** [SAFE-Stack/SAFE-ConfPlanner#70]
## Expected Behavior
After cloning the repository, running build.cmd or build.sh should build the whole project

## Current Behavior
build.fsx errors out on lines 19. When that error is resolved, the build script will error on lines 107 and 
131.
## Possible Solution
As a workaround, I hardcoded the value for dotnetcliVersion to "3.1" on line 19.  Someone who knows Fake better than I do could implement a real fix.
Lines 107 and 131 need to be updated to remove the path to webpack.config.js. Those lines should be:
`run yarnTool "webpack --config webpack.config.js -p" clientPath`

## Steps to Reproduce
1. Clone the repository.
2. Run build.cmd (or build.sh on Unix)

**Comment by rommsen** [comment]
Hi there. I have updated the readme. No more fake for now. Will maybe readd at some point but everything should work now
